### ISSUE TITLE
Cannot Get Docker Image

### ISSUE THREAD

**Issue by YvesLangstonMays** [karl-cardenas-coding/mywhoop#27]
failed to resolve reference "ghcr.io/karl-cardenas-coding/mywhoop:v0.1.2": unexpected status from HEAD request to https://ghcr.io/v2/karl-cardenas-coding/mywhoop/manifests/v0.1.2: 403 Forbidden

**Comment by karl-cardenas-coding** [comment]
@YvesLangstonMays Try again. I forgot to make the package public so it should work now.
